version: '3'
services:
  web:
    env_file: .env
    build: .
    ports:
    - "3000:3000"
    depends_on:
      - redis
      - elasticsearch
    image: index.docker.io/mmmanyfold/cfd:latest
  redis:
    image: "redis:alpine"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.4.1"
  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
    command: --interval 30 --debug web
    restart: unless-stopped
