version: '3'
services:
  web:
    env_file: .env
    build: .
    ports:
    - "3000:3000"
    depends_on:
      - redis
      - elasticsearch
  redis:
    image: "redis:alpine"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.4.1"
