version: '3'
services:
  web:
    env_file: .env
    build: .
    ports:
    - "3000:3000"
  redis:
    image: "redis:alpine"
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.4.1"
