version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.1.10-node-browsers
    steps:
    - checkout
    - setup_remote_docker
    - run: |
        sudo make compose-build
workflows:
  version: 2
  build_and_deploy:
    jobs:
    - build
    - deploy_prod:
        requires:
        - build
        filters:
          branches:
            only:
            - feat-circle
